locals {
  regions = {
    "eastus"             = "eaus1"
    "eastus2"            = "eaus2"
    "southcentralus"     = "scus1"
    "westus2"            = "weus2"
    "westus3"            = "weus3"
    "australiaeast"      = "eaau1"
    "southeastasia"      = "seas1"
    "northeurope"        = "noeu1"
    "swedencentral"      = "cesw1"
    "uksouth"            = "souk1"
    "westeurope"         = "weeu1"
    "centralus"          = "ceus1"
    "northcentralus"     = "ncus1"
    "westus"             = "weus1"
    "southafricanorth"   = "soan1"
    "centralindia"       = "cein1"
    "eastasia"           = "eaas1"
    "japaneast"          = "eajp1"
    "jioindiawest"       = "weji1"
    "koreacentral"       = "ceko1"
    "canadacentral"      = "ceca1"
    "francecentral"      = "cefr1"
    "germanywestcentral" = "wcge1"
    "norwayeast"         = "eanw1"
    "switzerlandnorth"   = "nosl1"
    "uaenorth"           = "noua1"
    "brazilsouth"        = "sobr1"
    "asia"               = "geas0"
    "asiapacific"        = "paas1"
    "australia"          = "geau0"
    "brazil"             = "gebr0"
    "canada"             = "geca0"
    "europe"             = "geeu0"
    "france"             = "gefr0"
    "germany"            = "gegr0"
    "global"             = "gegl0"
    "india"              = "gein0"
    "japan"              = "gejp0"
    "korea"              = "geko0"
    "norway"             = "genw0"
    "southafrica"        = "gesa0"
    "switzerland"        = "gesl0"
    "uae"                = "geua1"
    "uk"                 = "geuk1"
    "unitedstates"       = "geus0"
    "westcentralus"      = "wcus1"
    "southafricawest"    = "wesa1"
    "australiacentral"   = "ceau1"
    "australiacentral2"  = "ceau2"
    "australiasoutheast" = "seau1"
    "japanwest"          = "wejp1"
    "jioindiacentral"    = "ceji1"
    "koreasouth"         = "soko1"
    "southindia"         = "soin1"
    "westindia"          = "wein1"
    "canadaeast"         = "eaca1"
    "francesouth"        = "sofr1"
    "germanynorth"       = "nogr1"
    "norwaywest"         = "wenw1"
    "switzerlandwest"    = "wesl1"
    "ukwest"             = "weuk1"
    "uaecentral"         = "ceua1"
    "brazilsoutheast"    = "sebr1"
  }

  vm_data_disks = { for idx, data_disk in var.data_disks : data_disk.name => {
    idx : idx,
    data_disk : data_disk,
    }
  }

}
